// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-M9M2iLkSn_pY8g4lKvgYPXHjqMOiJvg',
    appId: '1:676988167299:android:5b176e1cce407185cb27b6',
    messagingSenderId: '676988167299',
    projectId: 'ttrail-3c6a9',
    databaseURL: 'https://ttrail-3c6a9-default-rtdb.firebaseio.com',
    storageBucket: 'ttrail-3c6a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRRudiy9bpiTNdPyacmdnF7PwN82_N780',
    appId: '1:676988167299:ios:ad9ef8e0e6a7151acb27b6',
    messagingSenderId: '676988167299',
    projectId: 'ttrail-3c6a9',
    databaseURL: 'https://ttrail-3c6a9-default-rtdb.firebaseio.com',
    storageBucket: 'ttrail-3c6a9.appspot.com',
    iosClientId: '676988167299-ar5ml7qg9nmj9dvbs1ssi5o67d29piao.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttrailLaptopo',
  );
}
